plugins { id 'com.android.application' }

android {
    namespace 'ru.gnvp.gortrainer'
    compileSdk 35

    defaultConfig {
        applicationId 'ru.gnvp.gortrainer'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '0.3'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
}
